### PR TITLE
Added support to nan@2.0.9

### PR DESCRIPTION
**Pull request by cronopio**
This commit add support to NAN with its latest changes.

### CODE REVIEW

**Comment by creationix** [comment]
This would be awesome.  Do you have any idea why it's breaking on appveyor (windows)?

**Comment by creationix** [comment]
I thought it was a temporary failure and re-started the tests, but it failed again at the same place getting the node checksum.

**Comment by cronopio** [comment]
@creationix Thanks for thaking a look, well I dont have idea about the issue with windows, almost none of experience on windows

**Comment by RangerMauve** [comment]
It's due to Node v4 borking things up with Node-gyp and npm on Windows. I'd suggest you configure it to use the latest v12 of node instead.

**Comment by cronopio** [comment]
Oh I see the issue. Node v4 is not providing `SHASUMS.txt` required by https://github.com/nodejs/node-gyp/blob/master/lib/install.js#L311 it was changed to `SHASUMS256.txt`

**Comment by martin-mh** [comment]
Is that issue will be fixed :) ? I'm not pro in nan and C++ addon for Node.js so i don't know how to take a deeper look on that ?

**Comment by Ajusa** [comment]
I need help with this! I am using the electron framework, and I think that this may be causing the issue. I will open a separate one if it is not related to this.

**Comment by deadprogram** [comment]
The @cronopio branch works great for me in Node 4.2 under Linux. We can take a look into the Windows build problem sometime in the next couple of weeks.

**Comment by deadprogram** [comment]
Hi @creationix friendly reminder to pretty please accept this PR and cut a new release. :wave:

**Comment by deadprogram** [comment]
Regarding the Appveyor build error for Windows, perhaps changing this line https://github.com/cronopio/node-gamepad/blob/nodev4/appveyor.yml#L60 to:

```
 - cmd: call nodist 4.3.3
```

Because from https://ci.appveyor.com/project/creationix/node-gamepad/build/1.0.14#L149 it appears to be pulling 4.0.0.

Or perhaps simply restarting the build on Appveyorwill accompish that?

**Comment by creationix** [comment]
restarted build

**Comment by deadprogram** [comment]
OK, well, obviously that did not work. Let me see if I can submit a PR that fixes the Windows build.

**Comment by deadprogram** [comment]
OK, my PR #10 fixes the Windows builds for 0.10, 0.12, 4.4, & 5.11

I propose merge this PR, and then merge my PR, and then cut a release. And then :beers: for everyone involved.

**Comment by creationix** [comment]
@deadprogram thanks for the tweaks. It seems to be working so far.

**Pull request merged**
