### PR TITLE
Use "prebuild" for creating and publishing binaries

### LINKED ISSUE #17: Move binary publishing to Github and off S3 bucket
We should move the hosting of the precompiled binaries off of the S3 bucket that we are curringly hosting, and onto Github.

### PR DESCRIPTION
**Pull request by Lange**
Closes #17.

This PR should provide almost everything needed to immediately start getting pre-built binaries automatically created and uploaded to GitHub for the following platforms:

- [x] Windows x86
- [x] Windows x64
- [x] Linux x86
- [x] Linux x64
- [x] macOS x64

All that needs to be done **before merging this PR** is to **replace my encrypted GitHub token** (the `prebuild_upload` environment variable) with your own:

1. Follow the steps outlined in the [prebuild docs](https://github.com/prebuild/prebuild#create-github-token) for creating a GitHub token with the appropriate scope permissions.
2. Use the [AppVeyor "Encrypt Data" page](https://ci.appveyor.com/tools/encrypt) to encrypt your token. Then, paste it over my encrypted token in line 4 of `appveyor.yml`.
3. [Install the TravisCI CLI.](https://github.com/travis-ci/travis.rb#installation)
4. From your local `node-gamepad` directory, run the following command to get your encrypted `prebuild_upload` env var with your token:

    ```bash
    travis encrypt prebuild_upload=YOUR_GITHUB_TOKEN_HERE
    ```
5. Copy the resulting output and paste it over mine in line 14 of `.travis.yml`.
6. Commit/push your changes, then merge this PR! :tada: If I've done everything right, tagged commits will trigger a build, and automatically publish their artifacts to the GitHub release. The release will also be created if it does not already exist.

Other Notes:
- This is more or less a straight copy/paste from https://github.com/MadLittleMods/node-usb-detection/pull/47.

### CODE REVIEW

**Comment by Lange** [comment]
You can see what these releases look like here: https://github.com/Lange/node-gamepad/releases

To test my build, simply run `npm i lange/node-gamepad` in any Node project. I tested on Windows x64, and the binaries installed no problem. I have not tested on any other platforms.

**Comment by Lange** [comment]
I had neglected to actually run the `test.js` file before opening this PR -- I got a little ahead of myself.

I've changed `gamepad.js` such that `test.js` now works as expected for me on my Windows 10 x64 PC with my wireless Xbox One controller:

```
C:\Users\vanca\Documents\Programming\node-gamepad>node test.js
Gamepad EventEmitter {
  context: { on: [Function] },
  init: [Function: init],
  shutdown: [Function: shutdown],
  numDevices: [Function: numDevices],
  deviceAtIndex: [Function: deviceAtIndex],
  detectDevices: [Function: detectDevices],
  processEvents: [Function: processEvents],
  path: 'C:\\Users\\vanca\\Documents\\Programming\\node-gamepad\\build\\Release\\gamepad.node',
  domain: null,
  _events: {},
  _eventsCount: 0,
  _maxListeners: undefined }
init
numDevices 0
attach 0 { deviceID: 0,
  description: 'XInput Controller 1',
  vendorID: 1118,
  productID: 654,
  axisStates: [ 0, 0, 0, 0, 0, 0 ],
  buttonStates:
   [ false,
     false,
     false,
     false,
     false,
     false,
     false,
     false,
     false,
     false,
     false,
     false,
     false,
     false,
     false ] }
move 0 0 0.0000152587890625 0 461558.59432543337
move 0 1 0.0000152587890625 0 461558.59459574084
move 0 2 0.0000152587890625 0 461558.594874735
move 0 3 0.0000152587890625 0 461558.59501142165
move 0 4 -1 0 461558.5952130026
move 0 5 -1 0 461558.59535633196
down 0 10 461562.51026849094
move 0 0 0.058579325675964355 0.0000152587890625 461562.51060241525
move 0 1 -0.039383530616760254 0.0000152587890625 461562.5108418086
move 0 2 0.0169832706451416 0.0000152587890625 461562.5109935691
move 0 3 0.038376450538635254 0.0000152587890625 461562.51114660705
up 0 10 461562.7092878726
down 0 13 461563.1412701539
up 0 13 461563.2742688476
```

**Comment by Lange** [comment]
I've updated the PR to squash the commits. I've also updated my test build: https://github.com/Lange/node-gamepad/releases/tag/v1.5.0

I tested the installation of pre-build binaries on these three platforms, all of which worked as expected:
- Windows 10 x64
- macOS High Sierra
- Ubuntu 16.04.2 LTS x64

I tested my Xbox One controller on these two platforms:
- Windows 10 x64: worked as expected, no issues.
- macOS High Sierra (wired only, via [360Controller](https://github.com/360Controller/360Controller)): it worked, but segfaulted with code `11` when I unplugged the controller from my macbook. This appears to be a known issue: https://github.com/creationix/node-gamepad/issues/15

Given that the installers work, and that the binaries seem to work as expected, I think this is good to merge and publish a new release.

**Comment by creationix** [comment]
Great work @Lange!

**Comment by creationix** [comment]
I manually did the PR merge in the CLI so I could insert a commit with my keys.  We'll see if this works...

**Comment by creationix** [comment]
It looks like my appveyor hasn't been hooked up for a couple years now.  Did we move that to someone else's appveyor account or something? https://ci.appveyor.com/project/creationix/node-gamepad

**Comment by creationix** [comment]
Weird, the github webhook url matches the one in my appveyor, the posts from github are getting 204 responses from appveyor.  But nothing seems to be triggering.

**Comment by Lange** [comment]
@creationix The binaries are currently being attached to the v1.4.2 tag, because `package.json` has not yet been bumped to `1.5.0`.

**Comment by creationix** [comment]
oops.

**Comment by creationix** [comment]
ok, bumped to 1.5.1 in package.json and ran the `make release` script.  It conflicted hard on `travis.yml`.  Do we still need the separate osx branch for this new build system?  If so, I might need some help resolving the conflict manually.  I'm not sure what all this means.

**Comment by Lange** [comment]
There is no need for a separate osx branch anymore. I totally overlooked the existing `Makefile` and didn't edit it at all to fit this pr -- apologies.

**Comment by Lange** [comment]
As for the AppVeyor issue, that is very strange and I've not encountered this before. The only things I can think to do are:

1. Delete and re-create the project on AppVeyor.
2. Contact AppVeyor support, who will probably take about a day to get back to you.

**Comment by creationix** [comment]
Rebuiding the appveyor project seemed to help.  I bumped the version again.  Hopefully this one will work...

**Comment by Lange** [comment]
`npm i creationix/node-gamepad` seems to work well on my Windows 10 x64 PC. I think you'll be in the clear to `npm publish` once the OSX builds are ready. 👍

**Comment by creationix** [comment]
Awesome

**Comment by creationix** [comment]
published!

**Pull request merged**
